-- DROP DATABASE WATTS_ON;
CREATE DATABASE IF NOT EXISTS WATTS_ON;
USE WATTS_ON;

CREATE TABLE IF NOT EXISTS TIPO_DADOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_TIPO_DADO VARCHAR(50),
    REPRESENTACAO VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS DADOS(
	ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_DADO VARCHAR(50),
    DESCRICAO_DADO VARCHAR(50),
    VALOR_DADO DECIMAL(10,2),
    ID_TIPO_DADO INT,
    FOREIGN KEY (ID)
    REFERENCES TIPO_DADOS(ID) 
);

INSERT INTO TIPO_DADOS VALUES(
	null,
    "AMPERE",
    "A"
);

SELECT * FROM TIPO_DADOS;
